house_bot/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.views.generic import TemplateView, RedirectView

from cook.views import MyContactFormView
from cook.forms import PasswordResetForm

# import html5_appcache
# html5_appcache.autodiscover()

from sitemap import *
sitemaps = {
    'pages':Sitemap(['sign up', 'sign up to group', 
                     'resend', 'create group',
                     'logout', 'login', 'close account', 'edit history', 'karma', 
                     'settings account', 'settings group', 'password update', 'password_reset', 
                     'password_reset_done', 'contact_form', 'quick choice']),
    'verify':Sitemap_Verify(['verify', 'password_reset_confirm']),
}

urlpatterns = patterns(
    '',

    # home
    url(r'^$', 'cook.views.index', name='home'),
    
    # registration
    url(r'^sign_up/$', 'cook.views.sign_up', name='sign up'),
    url(r'^sign_up_to_group/$', 'cook.views.sign_up_to_group', name='sign up to group'),
    url(r'^verify/(?P<uid>[0-9A-Za-z]+)-(?P<token>.+)/$', 'cook.views.verify', name="verify"),
    url(r'^resend/$', 'cook.views.resend_verification', name="resend"),
    url(r'^group_create/$', 'cook.views.create_group', name='create group'),
    url(r'^logout/$', 'cook.views.logout_view', name='logout'),
    url(r'^login/$', 'cook.views.login_view', name='login'),
    url(r'^close_account/$', 'cook.views.close_account', name='close account'),

    # history and karma
    url(r'^group_history/$', 'cook.views.edit_history_view', name='edit history'),
    url(r'^karma/$', 'cook.views.karma_view', name='karma'),

    # choice from email
    url(r'^quick_choice/(?P<uid>[0-9A-Za-z]+)-(?P<choice>[1-5])-(?P<token>.+)/$', 
        'cook.views.quick_choice', name="quick choice"),
    url(r'^quick_choice/(?P<uid>[0-9A-Za-z]+)/$', 
        'cook.views.quick_choice', name="quick choice"),
    url(r'^quick_choice/$', 
        'cook.views.quick_choice', name="quick choice"),

    # account settings
    url(r'^settings/account/$', 'cook.views.settings_account_view', name='settings account'),
    url(r'^settings/group/$', 'cook.views.settings_group_view', name='settings group'),
    url(r'^settings/$', RedirectView.as_view(url='/settings/account')),
    url(r'^password_update/$', 'cook.views.password_update_view', name='password update'),

    # password reset
    url(r'^password_reset/$', 
        'django.contrib.auth.views.password_reset', 
        {'post_reset_redirect' : '/password_reset/done/',
         'password_reset_form' : PasswordResetForm},
        name="password_reset"),
    url(r'^password_reset/done/$',
        'django.contrib.auth.views.password_reset_done'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 
        'django.contrib.auth.views.password_reset_confirm', 
        {'post_reset_redirect' : '/reset/done/'},
        name="password_reset_confirm"),
    url(r'^reset/done/$', 
        'django.contrib.auth.views.password_reset_complete',
        name="password_reset_done"),
    
    # enable admin documentation
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    # enable the admin
    url(r'^admin/', include(admin.site.urls)),
    
    # captcha
    url(r'^captcha/', include('captcha.urls')),

    # contact us
    url(r'^contact$', MyContactFormView.as_view(), name='contact_form'),   

    # sitemap
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps }), 

    # cache manifest
    url(r'^manifest\.appcache$', TemplateView.as_view(template_name="manifest.appcache", content_type="text/cache-manifest"), 
        name='manifest'),
    url(r'^offline$', TemplateView.as_view(template_name="offline.html"), name='offline'),
)

cook/models.py
from django.db import models
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login
from django.core.exceptions import ObjectDoesNotExist

import string, pytz, random

from django.core import mail
from django.template.loader import get_template
from django.template import Context
from django.conf import settings

from django.contrib.sites.models import get_current_site

# token generation
from datetime import datetime
from django.conf import settings
from django.utils.http import int_to_base36, base36_to_int
from django.utils.crypto import constant_time_compare, salted_hmac
from django.utils import six

class ChoiceSet(models.Model):
    text = models.CharField(max_length=200)

    def __unicode__(self):
        return unicode(self.text)

class Choice(models.Model):
    group = models.ForeignKey(ChoiceSet)
    choice_text = models.CharField(max_length=200)
    index = models.IntegerField()

    def __unicode__(self):
        return unicode(self.choice_text)

class Group(models.Model):
    id = models.CharField(primary_key=True, max_length=30)
    display_name = models.CharField(max_length=100)
    choice_set = models.ForeignKey(ChoiceSet)
    t_decision = models.IntegerField(default = 16)
    next_t_decision = models.IntegerField(default = 16)
    t_zone = models.CharField(max_length=30)
    active = models.BooleanField(default=False)

    @classmethod
    def create(cls):
        while True:
            id = ''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(30))
            try:
                group = Group.objects.get(id=id)
            except ObjectDoesNotExist:
                group = cls(id=id)
                return group

    def __unicode__(self):
        return unicode(self.display_name)

    @staticmethod
    def create_group(display_name, tz, emails, creator):
        group = Group.create()
        group.display_name = display_name
        group.t_zone = tz
        choices = ChoiceSet.objects.get(text='cook')
        group.choice_set = choices
        group.save()

        creator.cook_group = group
        now = datetime.utcnow()
        tz = pytz.timezone(group.t_zone)
        now_tz = now + tz.utcoffset(now)
        if now_tz.hour < group.t_decision:
            creator.choice_active = True
        creator.save()

        group.invite(emails, creator)

        return (0, 'Your group has been created successfully!')

    def invite(self, emails, invitor):
        
        connection = mail.get_connection()
        connection.open()
        messages = []
        html = get_template('registration/invitation.html')
        for email in emails:
            if email != '':
                content = Context({ 'email':email, 'cook_group':invitor.cook_group, 
                                    'member':invitor.get_name(),
                                    'domain':'www.house-bot.com'})
                subject, body = 'Your invitation to house-bot', html.render(content)
                from_email = 'house-bot'
                to = [email]
                messages.append(mail.EmailMessage(subject, body, from_email, to))
                messages[-1].content_subtype = "html"
        connection.send_messages(messages)
        connection.close()

    # def message(self, subject, body):
    #     from_email = 'house-bot'
    #     to = [member.user.email for member in Member.objects.filter(cook_group=self)]
    #     message = mail.EmailMessage(subject, body, from_email, to)
    #     message.content_subtype = "html"
    #     message.send()

class Member(models.Model):
    user = models.ForeignKey(User)
    cook_group = models.ForeignKey(Group, null=True, default=None)
    choice_active = models.BooleanField(default=False)
    choice = models.IntegerField(null=True, default=None)
    last_choice = models.IntegerField(null=True, default=None)
    points = models.FloatField(default = 0)
    t_morning = models.IntegerField(null=True, default=10)
    b_reminder = models.BooleanField(default=True)
    choice_token = models.CharField(null=True, default=None, max_length=200)
    always_notify = models.BooleanField(default=True)
    email_settings = models.BooleanField(default=True)
    email_history = models.BooleanField(default=True)

    def __unicode__(self):
        return unicode(self.user.username)

    def get_name(self):
        return self.user.first_name

    @staticmethod
    def create_member(email, password, display_name, cook_group):
        
        try:
            user = User.objects.get(email=email)
            return (1, 'A user already exists with this email address.')
        except ObjectDoesNotExist:
            while True:
                username = ''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(30))
                try:
                    user = User.objects.get(username=username)
                except ObjectDoesNotExist:
                    break

        user = User.objects.create_user(username, email, password)
        user.first_name = display_name
        user.save()
        
        member = Member()
        member.user = user
        if cook_group is not None:
            group = Group.objects.get(id=cook_group)
            member.cook_group = group
            token = None
            
            # decide whether choice is active or not
            now = datetime.utcnow()
            tz = pytz.timezone(group.t_zone)
            now_tz = now + tz.utcoffset(now)
            if now_tz.hour < group.t_decision:
                member.choice_active = True
        else:
            user.is_active = False
            user.save()
            
        member.last_choice = 0
        member.save()

        member.send_welcome_email()

        return (0, 'Your user account has been set up successfully. Welcome to house-bot')

    def send_welcome_email(self):
        html = get_template('registration/welcome_email.html')
        if not self.user.is_active:
            token = self.make_token()
        else:
            token = None
        content = Context({ 'member':self.get_name(), 'token':token, 'uid':self.user.username })
        subject, body = 'Welcome to house-bot', html.render(content)
        from_email = 'house-bot'
        to = [self.user.email]
        msg = mail.EmailMessage(subject, body, from_email, to)
        msg.content_subtype = "html"
        msg.send()

    @staticmethod
    def login(email, password, request):
        
        try:
            user = User.objects.get(email=email)
        except:
            return (1, 'The email/password combination was incorrect.')
        user = authenticate(username=user.username, password=password)
        if user is not None:
            login(request, user)
            return (0, 'You are now logged in')
        else:
            return (1, 'The email/password combination was incorrect.')

    """
    Strategy object used to generate and check tokens for member.
    """
    def make_token(self):
        """
        Returns a token that can be used once to do a password reset
        for the given user.
        """
        token = self._make_token_with_timestamp(self._now())
        self.choice_token = token
        self.save()
        return token

    def check_token(self, token):
        """
        Check that a password reset token is correct for a given user.
        """
        if self.choice_token == token:
            # set token to something unguessable
            self.choice_token = self._make_token_with_timestamp(self._now())
            return True
        
        return False

    def _make_token_with_timestamp(self, timestamp):
        user = self.user

        # timestamp is number of days since 2001-1-1.  Converted to
        # base 36, this gives us a 3 digit string until about 2121
        ts_b36 = int_to_base36(timestamp)

        # By hashing on the internal state of the user and using state
        # that is sure to change (the password salt will change as soon as
        # the password is set, at least for current Django auth, and
        # last_login will also change), we produce a hash that will be
        # invalid as soon as it is used.
        # We limit the hash to 20 chars to keep URL short
        key_salt = "django.contrib.auth.tokens.PasswordResetTokenGenerator"

        # Ensure results are consistent across DB backends
        login_timestamp = user.last_login.replace(microsecond=0, tzinfo=None)

        value = (six.text_type(user.pk) + user.password +
                six.text_type(login_timestamp) + six.text_type(timestamp))
        hash = salted_hmac(key_salt, value).hexdigest()[::2]

        return "%s-%s" % (ts_b36, hash)

    def _now(self):
        now = datetime.utcnow()
        return now.hour*now.minute*now.second*now.microsecond

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=425, initial-scale=0.8">
 		<link href='http://fonts.googleapis.com/css?family=Roboto:300,400' rel='stylesheet' type='text/css'/>
		<link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="{% static 'css/normalize.css' %}" />
    <link rel="stylesheet" href="{% static 'css/grid.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />		
	  <script type='text/javascript' src='http://code.jquery.com/jquery-1.8.1.min.js'/></script>
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
			
			ga('create', 'UA-45019164-1', 'house-bot.com');
			ga('send', 'pageview');
		</script>
    <title>{% block title %}{% endblock %}</title>
	</head>
	
	<body>
		<div id="non-footer" class="b-grad-blue">
			<div id="header" class="full-width thin-min shadow-blue">
				<div class="container_16 thin clearfix">
					<div class="left">
						<a href="/"><img class="logo" src="{% static 'svg/header-title.svg' %}" alt="house-bot"/></a>
					</div>
					<div class="toolbar right">
						{% if user.is_authenticated %}
						<ul class="right">
							{% if not no_settings and user.is_active %}
							<a href="{% url 'settings account' %}"><li>
									<img src="{% static 'svg/settings.svg' %}" alt="settings" title="settings"/>
							</li></a>
							{% endif %}
							<a href="{% url 'logout' %}"><li>
									<img src="{% static 'svg/logout.svg' %}" alt="logout" title="logout"/>
							</li></a>
						</ul>
						{% else %}
						<ul class="right center">
							<a href="{% url 'login' %}"><li class="button">Log in</li></a>
							<a href="{% url 'sign up' %}"><li class="button">Sign up</li></a>
						</ul>
						{% endif %}
					</div>
				</div>
			</div> <!-- header -->
			
			{% if messages %}
			<div id="messages" class="container_16 thin clearfix messages green d-shadow-blue-2 center txt-white">
				<ul>
					{% for message in messages %}
					<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					{% endfor %}
				</ul>
			</div>
			{% endif %}
			
			<div id="main" class="container_16 thin before-footer center">
				{% block content %}{% endblock %}
			</div>
		</div> <!-- #non-footer -->
			
    <div id="footer" class="b-darkgrey txt-grey footer">
			<div class="container_16 thin center clearfix">
				<a class="contact clearfix" href="{% url 'contact_form' %}">
					<p>
						<img src="{% static 'img/contact.png' %}" />
						CONTACT US - we would love to hear your feedback
					</p>
				</a>
				<!-- <p>&copy; house-bot 2013&nbsp;&nbsp;</p> -->
			</div>
	  </div> <!-- #footer -->

		<script type="text/javascript" language="Javascript">
      
		  function set_form() {
					if ($(window).width() > 610) {
							$("#form").removeClass('thin-form').addClass('form')
					}
					else {
							$("#form").removeClass('form').addClass('thin-form')
					}
			}

      window.addEventListener('DOMContentLoaded', function(e) {
					set_form();
      }, false)

      window.onload = function() {
					set_form();
      };

      window.onresize = function() {
					set_form();
      };

			$("#messages").click(function() {
					// alert( "Handler for .click() called." );
					$("#messages").slideUp( 200, function() {
					})
			})										
		</script>
  </body>

</html>

templates/choice_form.html
{% load staticfiles %}
<div class="choices">
	<img class="question" src="{% static 'svg/can_you_cook.svg' %}" alt="can you cook?"/>
	{% for choice in member.cook_group.choice_set.choice_set.all %}
	<form action="{{ url }}" method="post">
		{% csrf_token %}
		<input type="hidden" name="index" value={{ choice.index }} />
		{% if choice.index == member.choice %}
		<input type="submit" class="selected" value="{{ choice.choice_text }}" />
		{% else %}
		<input type="submit" class="unselected" value="{{ choice.choice_text }}" />
		{% endif %} 
	</form>
{% endfor %}
</div>

templates/choice_made.html
{% load staticfiles %}
<div class="choices">
	<h2>Result coming soon!</h2>
	<form>
		{% for choice in member.cook_group.choice_set.choice_set.all %}
		{% if choice.index == member.choice %}
		<input type="submit" class="selected" value="{{ choice.choice_text }}" />
		{% endif %} 
		{% endfor %}
	</form>

	<p>House bot is working on it. The decision will be made at {{member.cook_group.t_decision}}:00</p>

	<form action="{{ url }}" method="post">
		{% csrf_token %}
		<input type="hidden" name="reset" value="" />
		<input type="submit" class="unselected" value="change my choice" />
	</form>
</div>

templates/decision_made.html
{% load staticfiles %}
<div class="choices people-list">
	{% if member.cook_group.active %}
	<h1>Decision made</h2>
  <div class="hr">
	</div>
	<ul>
		{% for m in sorted_members %}
		<li>{{m.user.first_name}}: {% if m.last_choice == 2 %}
			<img src="{% static 'svg/cooker.svg' %}" alt="cooker" title="cooker"/>
			{% elif m.last_choice == 1 %}
		<img src="{% static 'svg/eater.svg' %}" alt="eater" title="eater"/>
		{% else %}
		<img src="{% static 'svg/none.svg' %}" alt="not in" title="not in"/>
		{% endif %}
		</li>
		{% endfor %}
	</ul>
  <p>You will be able to make your choice for tomorrow from 1am.</p>
	{% else %}
	<h1>See you tomorrow</h2>
  <div class="hr"></div>
  <p>Your group will become active tomorrow morning and you will then be able to make choices for the evening's communal cooking. We will also send you an email with the available choices.</p>
  <p>We look forward to seeing you then.</p>
{% endif %}
  <div class="hr"></div>
</div>

templates/edit_history.html
{% extends "base.html" %}

{% block title %}house-bot | edit history{% endblock %}

{% block content %}
<h1>Edit history</h2>
<p>Change the result of the last decision that was made.</p>
<div id="edit-history" class="form edit-history">
  <form method="post" action="{% url 'edit history' %}" id="account_settings_form">
    {% csrf_token %}
    <div class="hr"></div>
		{% for field in form %}
    <div class="form-fieldwrapper clearfix">
      {{ field.errors }}
      <label class="" for="{{ field.id }}">{{ field.label }} </label>
			{{ field }}
    </div>
    {% endfor %}
    <div class="hr"></div>
		<div class="form-submitwrapper cancel clearfix">
			<ul>
				<a href="{% url 'home' %}">
					<li>
						Cancel
					</li>
				</a>
			</ul>	
			<input type="submit" class="button" value="Update" />
		</div>
  </form>
</div>
{% endblock content %}

templates/group_set_up.html
{% extends "base.html" %}

{% block title %}house-bot | create your group{% endblock %}

{% block content %}
<p>Hello {{ display_name }}. We are very excited to have you on board. It is now time to form your cooking group.</p>

<div id="form" class="form txt-white">
	<form method="post" action="{% url 'create group' %}" name="group_name_form" id="group_name_form">
		{% csrf_token %}
		{{ form.non_field_errors }}
		<div class="form-fieldwrapper clearfix">
			{{ form.display_name.errors }}
			<label class="" for="display_name">{{ form.display_name.label }}</label>
			{{ form.display_name }}
		</div>
		<div class="form-fieldwrapper clearfix">
			{{ form.tz.errors }}
			<label class="" for="tz">{{ form.tz.label }}</label>
			{{ form.tz }}
		</div>
		<div class="form-fieldwrapper clearfix">
			{{ form.email_addresses.errors }}
			<label class="" for="email_addresses">
				{{ form.email_addresses.label }}</br>
				<span class="help">{{ form.email_addresses.help_text }}</span>
			</label>
			{{ form.email_addresses }}
		</div>
		<div class="form-submitwrapper clearfix">
			<input type="submit" class="button" value="Create your group" />
		</div>
	</form>
</div>

{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}house-bot{% endblock %}

{% block content %}
{{ home_content }}
<div class="choices clearfix edit_karma_bar">
	<ul>
		{% if member.cook_group.active %}
		<a class="txt-white" href="{% url 'edit history' %}">
			<li class="">
				<img src="{% static 'svg/edit_arrow.svg' %}" />
				{{edit_text}}
			</li>
		</a>
		<a class="txt-white" href="{% url 'karma' %}">
			<li class="">
				<img src="{% static 'svg/edit_arrow.svg' %}" />
				view karma
			</li>
		</a>
		{% endif %}
	</a>
	<span class="txt-small">
		<p>Logged in as <strong>{{ member.user.first_name }}</strong> in <strong>{{ member.cook_group.display_name }}</strong></p>
	</span>
</div>
{% endblock content %}

templates/login.html
{% extends "base.html" %}

{% block title %}house-bot | log in{% endblock %}

{% block content %}
<div id="form" class="form">
  <form method="post" action="{% url 'login' %}" id="login_form">
    {% csrf_token %}
		{{ form.non_field_errors }}
		<div class="form-fieldwrapper clearfix">
			{{ form.email.errors }}
			<label class="" for="email">{{ form.email.label }}</label>
			{{ form.email }}
		</div>
		<div class="form-fieldwrapper clearfix">
			{{ form.password.errors }}
			<label class="" for="password">{{ form.password.label }}</label>
			{{ form.password }}
		</div>
		<div class="form-submitwrapper clearfix">
			<input type="submit" class="button" value="Log in" />
		</div>
		<div class="hr"></div>
		<div class="form-fieldwrapper password_reset clearfix">
			{{ form.remeber.errors }}
			<label class="check_label" for="remember">{{ form.remember.label }}</label>
			{{ form.remember }}
			<ul>
				<li>
					<a href="{% url 'password_reset' %}">
						I have forgotten my password
					</a>
				</li>
			</ul>
		</div>
  </form>
</div>
{% endblock content %}

templates/offline.html
{% load staticfiles %}
<!DOCTYPE html>
<html manifest="manifest.appcache">
	<head>
		<meta name="viewport" content="width=425, initial-scale=0.8">
 		<!-- <link href='http://fonts.googleapis.com/css?family=Roboto:300,400' rel='stylesheet' type='text/css'/> -->
		<!-- <link rel="stylesheet" href="{% static 'css/normalize.css' %}" /> -->
    <!-- <link rel="stylesheet" href="{% static 'css/grid.css' %}"/> -->
    <!-- <link rel="stylesheet" href="{% static 'css/base.css' %}"/> -->
		<!-- <link rel="stylesheet" href="{% static 'css/main.css' %}"/> -->
    <!-- <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />	 -->
    <title>house-bot | offline</title>
	</head>
	
	<body>
		<div id="non-footer" class="b-grad-blue">
			<div id="header" class="full-width thin-min shadow-blue">
				<div class="container_16 thin clearfix">
					<div class="left">
						hello
						<!-- <a href="/"><img class="logo" src="{% static 'svg/header-title.svg' %}" alt="house-bot"/></a> -->
					</div>
				</div>
			</div> <!-- header -->
			
			<div id="main" class="container_16 thin center before-footer center">
				<p>
					You are currently offline. Please come back when you have an internet connection.
				</p>
			</div>
		</div> <!-- #non-footer -->
			
    <div id="footer" class="b-darkgrey txt-grey footer">
			<div class="container_16 thin center clearfix">
				<p>
					offline
				</p>
				<p>&copy; house-bot 2013&nbsp;&nbsp;</p>
			</div>
	  </div> <!-- #footer -->
  </body>

</html>

templates/password_update.html
{% extends "base.html" %}

{% block title %}house-bot | password update{% endblock %}

{% block content %}
<div id="form" class="form">
  <form method="post" action="{% url 'password update' %}" id="password_update_form">
    {% csrf_token %}
		{{ form.non_field_errors }}
		<div class="form-fieldwrapper clearfix">
			{{ form.old_password.errors }}
			<label class="" for="old_password">{{ form.old_password.label }}</label>
			{{ form.old_password }}
		</div>
		<div class="form-fieldwrapper clearfix">
			{{ form.password1.errors }}
			<label class="" for="password1">{{ form.password1.label }}</label>
			{{ form.password1 }}
		</div>
		<div class="form-fieldwrapper clearfix">
			{{ form.password2.errors }}
			<label class="" for="password2">{{ form.password2.label }}</label>
			{{ form.password2 }}
		</div>
		<div class="form-submitwrapper clearfix">
			<input type="submit" class="button" value="Submit" />
		</div>
  </form>
</div>
{% endblock content %}

templates/points.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}house-bot | karma{% endblock %}

{% block content %}
<div class="people-list">
	<h1>Karma</h2>
  <div class="hr"></div>
	<ul>
		{% for m in member.cook_group.member_set.all %}
		<li>{{m.user.first_name}}: {{ m.points }}</li>
		{% endfor %}
	</ul>
	<div class="home clearfix">
		<ul>
			<a href="{% url 'home' %}">
				<li>
					Back to home page
				</li>
			</a>
		</ul>	
	</div>
</div>
{% endblock content %}

templates/settings.html
{% extends "base.html" %}

{% block title %}house-bot | settings{% endblock %}

{% block content %}
<ul class="button_menu">
	<a href="{% url 'home' %}"><li class="home">
			Home
	</li></a>
	{% if account %}
	<a href="{% url 'settings account' %}"><li class="green">
			Account
	</li></a>
	<a href="{% url 'settings group' %}"><li>
			Group
	</li></a>
	{% else %}
	<a href="{% url 'settings account' %}"><li>
			Account
	</li></a>
	<a href="{% url 'settings group' %}"><li class="green">
			Group
	</li></a>
	{% endif %}
</ul>	
<div id="form" class="form">
  <form method="post" action="{{ url }}" id="account_settings_form">
    {% csrf_token %}
		<div class="hr"></div>
		{% block settings_form %}{% endblock settings_form %}
		<div class="form-submitwrapper clearfix">
			<input type="submit" class="button" value="Update" />
		</div>
  </form>
</div>
{% endblock content %}

templates/settings_group.html
{% extends "settings.html" %}

{% block settings_form %}
{{ form.non_field_errors }}
<h2>Group Settings</h2>
<div class="form-fieldwrapper clearfix">
	{{ form.display_name.errors }}
	<label class="" for="email">{{ form.display_name.label }}</label>
	{{ form.display_name }}
</div>
<div class="form-fieldwrapper clearfix">
	{{ form.t_decision.errors }}
	<label class="" for="t_decision">
		{{ form.t_decision.label }}</br>
		<span class="help">{{ form.t_decision.help_text }}</span>
	</label>
	{{ form.t_decision }}
</div>
<div class="form-fieldwrapper clearfix">
	{{ form.tz.errors }}
	<label class="" for="tz">{{ form.tz.label }}</label>
	{{ form.tz }}
</div>
<div class="hr"></div>
<h2>Members</h2>
<div class="form-fieldwrapper clearfix members">
	<label class="" for="members">Current members</label>
	<ul>
		{% for member in members %}
		<li class=""><strong>{{ member.user.first_name }}</strong>: {{ member.user.email }}</li>
		{% endfor %}
	</ul>
</div>
<div class="form-fieldwrapper clearfix short">
	{{ form.email_addresses.errors }}
	<label class="" for="email_addresses">
		{{ form.email_addresses.label }}</br>
		<span class="help">{{ form.email_addresses.help_text }}</span>
	</label>
	{{ form.email_addresses }}
</div>
<div class="hr"></div>
{% endblock settings_form %}